In [3]:
#@title Mount Google Drive
from google.colab import drive
drive.mount('drive')

Mounted at drive

In [1]:
pip install kafka-python

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting kafka-python
  Downloading kafka_python-2.0.2-py2.py3-none-any.whl (246 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 246.5/246.5 KB 3.2 MB/s eta 0:00:00
Installing collected packages: kafka-python
Successfully installed kafka-python-2.0.2

In [4]:
import pandas as pd
from kafka import KafkaProducer
from time import sleep
from json import dumps
import json

In [5]:
PublicIP = '3.238.16.255:9092'#@param {type:"string"}
DataLocation = '/content/drive/My Drive/DataScienceProject/BlackFriday.csv'#@param {type:"string"}

In [6]:
producer = KafkaProducer(bootstrap_servers=[PublicIP],
                         value_serializer=lambda x: 
                         dumps(x).encode('utf-8'))

In [8]:
producer.send('Sales', value={'sale':'$10,000'})   #we have topic named as Sales

In [9]:
df = pd.read_csv(DataLocation)

In [10]:
df.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969

In [15]:
while True:
    dict_stock = df.sample(1).to_dict(orient="records")[0]
    producer.send('Sales', value=dict_stock)
    sleep(1)

KeyboardInterrupt: ignored

In [13]:
producer.flush() #clear data from kafka server